name: Register Package (Reusable)

on:
  workflow_call:

permissions:
  contents: write

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'
      - name: Register Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          julia --project=@register -e '
            using Pkg, TOML, LocalRegistry
            project = TOML.parsefile("Project.toml")
            package_name = project["name"]
            registry = "https://github.com/ClimFlows/JuliaRegistry.git"
            register(registry, package_name, ".")
          '
